regCenter:
  serverList: 10.2.3.41:2181
  namespace: elastic-job-lite-springboot

simpleJob:
  cron: 0/5 * 4 * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
  
dataflowJob:
  cron: 0/10 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

spring:
  profiles:
    active: dev
